### ISSUE TITLE
nbgv install fails to complete

### ISSUE THREAD

**Issue by sxotney** [dotnet/Nerdbank.GitVersioning#541]
After running ngbv install, a version.json is built and then the following error is returned to the console:

Unhandled Exception:
   Cannot print exception string because Exception.ToString() failed.

No build props are generated either. Not sure where to look? Any help greatly appreciated.

Many thanks,
Carl

**Comment by AArnott** [comment]
Thanks for your report, @sxotney. We'll need more info to make this actionable. At the very least, which version of `nbgv` are you using? Does the latest version repro the problem?

Also if you can provide repro steps that would be great. Otherwise, please try running `nbgv` under a debugger that breaks on first chance exceptions and share the resulting initial exception as well as the subsequent exception thrown from `Exception.ToString()` as there seems to be at least two bugs here.

**Comment by pg-entelect** [comment]
Repro steps

- Install the nbgv .NET Core CLI tool globally with
`dotnet tool install -g nbgv`
- Install the tool in the root of the repo with
`nbgv install`

Version: nbgv v3.3.37+0989e8fe0c

**Comment by AArnott** [comment]
I can't repro this. Can you point me to a git repo that shows the problem?

**Comment by pg-entelect** [comment]
I don't think this is a problem I can check into a repo. The nbgv CLI simply fails to complete an install. I've tried running it on an existing repo as well as a brand new empty one and both return the same error.

If you couldn't repro then it must be an edge case in my environment. Something that is absent or messing with the CLI.

**Comment by AArnott** [comment]
Ya, I tried with a brand new repo and it installed without an error. Although if you see this:

> Unhandled Exception:
Cannot print exception string because Exception.ToString() failed.

That suggests a double fail (a failure to print the message for a preceding failure). 

If you are interested, try running the `nbgv` tool from the repo's source within VS and find where the first and second exceptions are thrown.

**Comment by pg-entelect** [comment]
I have found the problem and it was indeed my environment.

It was unable to authenticate against one of my private NuGet feeds and fell over. Is there a way for me to limit it to only use the official NuGet repo until I sort out that private repo?

Error below:

```
NuGet.Protocol.Core.Types.FatalProtocolException
  HResult=0x80131500
  Message=Unable to load the service index for source https://pkgs.dev.azure.com/**<private NuGet feed redacted>**/nuget/v3/index.json.
  Source=NuGet.Protocol
  StackTrace:
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<TryCreate>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.DependencyInfoResourceV3Provider.<TryCreate>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<GetLatestVersionCoreAsync>d__94.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<>c__DisplayClass92_1.<<GetLatestVersionAsync>b__3>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<GetLatestVersionAsync>d__92.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Nerdbank.GitVersioning.Tool.Program.<GetLatestPackageVersionAsync>d__18.MoveNext() in C:\Source\Nerdbank.GitVersioning\src\nbgv\Program.cs:line 739
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Nerdbank.GitVersioning.Tool.Program.OnInstallCommand(String versionJsonRoot, String version, IReadOnlyList`1 sources) in C:\Source\Nerdbank.GitVersioning\src\nbgv\Program.cs:line 281
   at Nerdbank.GitVersioning.Tool.Program.MainInner(String[] args) in C:\Source\Nerdbank.GitVersioning\src\nbgv\Program.cs:line 161

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).

```

**Comment by AArnott** [comment]
Good find! Yes, I would favor a change so that we either always ignore nuget.config and always use nuget.org, or at least fail more gracefully on auth failures. 
Also, we should absolutely fix the error handling so that errors like this are actually printed to the console.
Can you send a PR?

**Comment by pg-entelect** [comment]
I'll see if I can make some time for it this week.

**Comment by pg-entelect** [comment]
The NuGet library supports `nuget.exe restore` options, so I was able to circumvent the broken source with

`nbgv install -s https://api.nuget.org/v3/index.json`

No code change is necessary, but the workaround should be added to the docs.

**Comment by AArnott** [comment]
Yes, the docs should be updated, I agree. I still think we should fix the error reporting as well.

**Comment by carlin-q-scott** [comment]
I don't think this is a documentation issue. Notice what the help command outputs for the default source when we have multiple sources configured:

> nbgv install --help
> install:
>   Prepares a project to have version stamps applied using Nerdbank.GitVersioning.
> 
> Usage:
>   nbgv install [options]
> 
> Options:
>   -p, --path <path>          The path to the directory that should contain the version.json file. The default is the root of the git repo.
>   -v, --version <version>    The initial version to set. [default: 1.0-beta]
>   -s, --source <source>      The URI(s) of the NuGet package source(s) used to determine the latest stable version of the Nerdbank.GitVersioning package. This setting
>                              overrides all of the sources specified in the NuGet.Config files. **[default: System.String[]]**
>   -?, -h, --help             Show help and usage information

It should default to the top source, which should always be nuget.org.

**Comment by xavierjohn** [comment]
nbgv install 
does crash for me with call stack
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Nerdbank.GitVersioning.Tool.Program.OnInstallCommand(String path, String version, IReadOnlyList`1 source) in D:\a\1\s\src\nbgv\Program.cs:line 258
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

version
nbgv v3.5.119+5d25f54fec

Repro: clone repository https://github.com/xavierjohn/FunctionalDDD
run 
nbgv install

even if you delete the version.json file, it will still fail.

I wonder if it has to do with 
```
<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
```
because it works fine on repos without ManagePackageVersionsCentrally
